/*
 * File: app/view/MainView.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('TestApp.view.MainView', {
    extend: 'Ext.container.Viewport',
    alias: 'widget.mainview',

    requires: [
        'TestApp.view.MainViewViewModel',
        'TestApp.view.MainViewViewController',
        'Ext.button.Button',
        'Ext.form.Panel',
        'Ext.form.field.Number',
        'Ext.form.RadioGroup',
        'Ext.form.field.Radio',
        'Ext.form.FieldSet',
        'Ext.form.field.Date',
        'Ext.form.field.Time'
    ],

    controller: 'mainview',
    viewModel: {
        type: 'mainview'
    },
    itemId: 'mainView',
    layout: 'border',

    items: [
        {
            xtype: 'panel',
            region: 'north',
            split: false,
            height: 60,
            itemId: 'headerPanel',
            title: 'Menu',
            items: [
                {
                    xtype: 'container',
                    layout: {
                        type: 'hbox',
                        align: 'stretch',
                        pack: 'center'
                    },
                    items: [
                        {
                            xtype: 'button',
                            text: 'One'
                        },
                        {
                            xtype: 'button',
                            text: 'Two'
                        },
                        {
                            xtype: 'button',
                            text: 'Three'
                        },
                        {
                            xtype: 'button',
                            text: 'Four',
                            listeners: {
                                click: 'onButtonClick'
                            }
                        },
                        {
                            xtype: 'button',
                            flex: 1,
                            text: 'MyButton'
                        }
                    ]
                }
            ]
        },
        {
            xtype: 'panel',
            region: 'center',
            split: true,
            itemId: 'centerPanel',
            title: 'Appendix',
            items: [
                {
                    xtype: 'container',
                    layout: {
                        type: 'hbox',
                        align: 'stretch',
                        pack: 'center'
                    },
                    items: [
                        {
                            xtype: 'form',
                            height: 268,
                            width: 570,
                            bodyPadding: 10,
                            title: 'Form',
                            items: [
                                {
                                    xtype: 'textfield',
                                    anchor: '100%',
                                    fieldLabel: 'Full name:'
                                },
                                {
                                    xtype: 'textfield',
                                    anchor: '100%',
                                    fieldLabel: 'Full address:',
                                    name: 'fullAddress'
                                },
                                {
                                    xtype: 'numberfield',
                                    anchor: '100%',
                                    width: 549,
                                    fieldLabel: 'Age'
                                },
                                {
                                    xtype: 'radiogroup',
                                    width: 400,
                                    fieldLabel: 'Gender:',
                                    items: [
                                        {
                                            xtype: 'radiofield',
                                            boxLabel: 'Male'
                                        },
                                        {
                                            xtype: 'radiofield',
                                            boxLabel: 'Female'
                                        }
                                    ]
                                },
                                {
                                    xtype: 'container',
                                    layout: {
                                        type: 'hbox',
                                        align: 'stretch',
                                        pack: 'end'
                                    },
                                    items: [
                                        {
                                            xtype: 'button',
                                            text: 'Submit',
                                            listeners: {
                                                click: 'onButtonClick1'
                                            }
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'container',
                    items: [
                        {
                            xtype: 'fieldset',
                            title: 'My Fields',
                            layout: {
                                type: 'vbox',
                                align: 'stretch',
                                pack: 'center'
                            },
                            items: [
                                {
                                    xtype: 'textfield',
                                    width: 531,
                                    fieldLabel: 'Full name:'
                                },
                                {
                                    xtype: 'textfield',
                                    width: 531,
                                    fieldLabel: 'Full address:'
                                },
                                {
                                    xtype: 'numberfield',
                                    fieldLabel: 'Time'
                                },
                                {
                                    xtype: 'datefield',
                                    fieldLabel: 'Today:'
                                },
                                {
                                    xtype: 'timefield',
                                    fieldLabel: 'Time:'
                                }
                            ]
                        }
                    ]
                }
            ]
        },
        {
            xtype: 'panel',
            region: 'west',
            split: true,
            itemId: 'leftPanel',
            width: 119,
            layout: 'accordion',
            title: 'Poll',
            dockedItems: [
                {
                    xtype: 'checkboxfield',
                    dock: 'top',
                    fieldLabel: 'Red',
                    boxLabel: 'Box Label'
                },
                {
                    xtype: 'checkboxfield',
                    dock: 'top',
                    fieldLabel: 'Green',
                    boxLabel: 'Box Label'
                },
                {
                    xtype: 'checkboxfield',
                    dock: 'top',
                    fieldLabel: 'Blue:',
                    boxLabel: 'Box Label'
                }
            ]
        },
        {
            xtype: 'panel',
            region: 'south',
            split: false,
            height: 85,
            itemId: 'footerPanel',
            title: 'Footer'
        }
    ]

});